version: '3.9' # optional since v1.27.0
services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=dbportugues
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=pass
    ports:
      - '5432:5432'
    volumes:
      - ./data_postgres:/var/lib/postgresql/data